# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "7064:7064"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7064
      - ASPNETCORE_HTTPS_PORT=7064
      - ASPNETCORE_Kestrel__Certificates__Default__Password=@321tankado
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
    volumes:
      - ${HOME}/.aspnet/https:/root/.aspnet/https

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@321tankado
